version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/app:/app
    restart: always
    depends_on:
      - db  # ✅ 数据库依赖
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/paralegal_db  #  .env 中未定义此项

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: paralegal_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
